### ISSUE TITLE
Add integration icon & logo in home-assistant/brands

### ISSUE THREAD

**Issue by mathoudebine** [chris60600/pollens-home-assistant#11]
Hello ! Just wanted to log here that i added an icon & logo for this integration !
I used the official RNSA logo from their website
The related PR : https://github.com/home-assistant/brands/pull/3537
It has been approved and merged so in you HomeAssistant you should now have it : 
![image](https://user-images.githubusercontent.com/38615348/180736474-c5f5d3f3-1146-43fc-a60f-f45bee1ade30.png)
![image](https://user-images.githubusercontent.com/38615348/180736623-d4cfd481-b926-4aaf-8200-16087a648bcc.png)
So this issue can be closed 😄 
Thanks for this integration, i use it everyday!

**Comment by chris60600** [comment]
Thank you ! I've never have the time to simply do it. 
(I wondered if I had the right to take their logo, which does not belong to me

In french : Merci, je n'ai jamais pris le temps de m'en occuper. (en même temps je me suis demandé si j'avais le droit de prendre leur logo, qui ne m'appartient pas)

**Comment by mathoudebine** [comment]
I had the same question in mind, but there is a Trademark Legal Notices on the front page that says "All product names, trademarks and registered trademarks in the images in this repository, are property of their respective owners." so it should be okay 👍
