### ISSUE TITLE
delleting a department does not release it in the integration

### ISSUE THREAD

**Issue by FROlCi** [chris60600/pollens-home-assistant#14]
let's says that I have 91 (essonne) added but I did not select all allergies.... as I have not found a way to add the missing one I decide to delete 91 hoppping that I will be add it again and then select all allegies... it would be nice to be able to add any missing allergies and even more cooler to consider that by default all allegies are elligible and selected by default

**Comment by Gilles2senior** [comment]
+1 on the possibility to add new allergies at a later stage when one didn't select all initially. Is the current recommendation to delete the integration and re-add from scratch?

**Comment by chris60600** [comment]
In version 2023.06.1
