### ISSUE TITLE
Better general status icon?

### ISSUE THREAD

**Issue by Gonioul** [chris60600/pollens-home-assistant#18]
Pollen general status currently uses mdi:decagram-outline

I think it should use mdi:flower-pollen

Risklevel should also be changed, but I didn't find any suitable icon.

**Comment by chris60600** [comment]
Hello,
Why a Flower ?  Why not grass or a tree? Taste and colours...
With HomeAssistant, you can customize your sensors and change icon with another you perfer... So I think decagram can be more generic !

**Comment by chris60600** [comment]
.
