### ISSUE TITLE
"Loire-Atlantique" not defined

### ISSUE THREAD

**Issue by Theodine** [chris60600/pollens-home-assistant#21]
"Loire-Atlantique" is not avalaible in the list to select the french department.

**Comment by chris60600** [comment]
Hello, 
I can select "Loire-Atlantique" (in position 44)  
![image](https://github.com/chris60600/pollens-home-assistant/assets/57842361/ccbfe5d5-dc17-4ff4-9de8-03f1bd0f3219)
Everything seems right
![image](https://github.com/chris60600/pollens-home-assistant/assets/57842361/dd4f3755-aecc-4911-9a13-99a7ef9c4956)

**Comment by chris60600** [comment]
Closed
