### ISSUE TITLE
Problem installation

### ISSUE THREAD

**Issue by Mick51** [chris60600/pollens-home-assistant#8]
![Capture d’écran 2022-02-04 234044](https://user-images.githubusercontent.com/40418405/152613176-b380cbe9-81b7-47ef-a785-84c84abe0ddf.jpg)

Problème avec la dernière version de HA.

`Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:164
Integration: Capteur ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 23:44:50 (1 occurrences)
Last logged: 23:44:50

The pollens platform for the sensor integration does not support platform setup. Please remove it from your config.`

**Comment by chris60600** [comment]
The configuration via configuration.yaml in now deprecated and must be removed
