### ISSUE TITLE
Main sensor still in text format

### ISSUE THREAD

**Issue by DominiqueRT** [chris60600/pollens-home-assistant#9]
Pollens home assistant : **v2022.02.02**

Even if sensor if configurated in  numeric, the main sensor for the region remains in text format.
<img width="780" alt="image" src="https://user-images.githubusercontent.com/7418677/152634358-771f10cd-a8f6-450e-bacc-2d77da4ae9b2.png">

eg : sensor.pollens_14 = faible instead of 1

**Comment by chris60600** [comment]
Its not a bug. The main sensor is left in the original form (like in the first version). Maybe a new numeric sensor in fire release.

**Comment by chris60600** [comment]
Add a new sensor with "_num" for numeric level value ex: sensor.pollens_14_num

**Comment by chris60600** [comment]
@all-contributors please add @mathoudebine for code
